### ISSUE TITLE
Parandada liikumine

### ISSUE THREAD

**Issue by markotaht** [markotaht/Portals#2]
Kaamera liigutamine võiks olla parem ja sujuvam saab paremini testida protaalide tööd.

**Comment by dianx93** [comment]
tagasi liikudes läheb pärast ise tagasi
ehk hoian S-i all, lähen tahapoole
lasen S-i lahti, kaamera liigub ettepoole

**Comment by dianx93** [comment]
never mind, sa panid piirajad
