### ISSUE TITLE
Uurida rekursiivset vaadet läbi portaali

### ISSUE THREAD

**Issue by markotaht** [markotaht/Portals#5]
Hetkel läbi portaali teist portaali ei näe. Oleks vaja tekitada tunnel.(Varasemalt töötas 2 kaamera ja 2 tekstuuriga, hetke lahendus seda ei võimalda.) Parema portaali tunde saamiseks kasutada stencil buffrit(hetkel kasutuses).

**Comment by markotaht** [comment]
Võimalik lahendus, teha stencil bufferiga 2-3 sügavusele ja edasi minna tekstuuridega.

**Comment by dianx93** [comment]
Võiks ära ka teha

**Comment by markotaht** [comment]
Valmis, hetkel on sügavus 3-4 rohkemega on jube lagg.
