### ISSUE TITLE
Parandada valgus

### ISSUE THREAD

**Issue by dianx93** [markotaht/Portals#6]
Valguskera paistab olevat punase kera taga, punase kera ees on valguslaik...

**Comment by dianx93** [comment]
portaalides on valgusega mingi imelik värk, kui minna läbi lilla seina, on valgus nagu portaalist näha oli, kui minna läbi rohelise, siis on valgus hoopis teises kohas kui portaalist paistis... Weird
"rohelises" toas tundub läbi portaali valgus peaaegu paigal olevat.

**Comment by markotaht** [comment]
Minna üle ThreeJS materjalidele ja kasutada lightingut mis on THREEJS poolt pakutud, lihtsustab koodi.

**Comment by dianx93** [comment]
Portaalidesse tundub valgus tulevat ainult sealt ruumist, kus oled. Kommenteerisin mõned read light.set / lightPosition.set välja, aga see ei näi midagi mõjutavat, vajab uurimist.
