### ISSUE TITLE
Kujundada maailm

### ISSUE THREAD

**Issue by markotaht** [markotaht/Portals#8]
Seinad ja objektid võiksid olla tektuuridega. 

Ülejäänud maailma võib ka huvitavamaks teha, et ei oleks lihtsalt 1 tuba 4 seinaga.

Lisada sisse ka vb kasutajale mingi mudel ja siis sellega liikuda (nt see marine mudelite importimise praksist)

**Comment by dianx93** [comment]
tegin ruumi ilusamaks

**Comment by dianx93** [comment]
https://github.com/markotaht/Portals/commit/2390e5f015ff83bbe4a8e4ec699352e889ba81ca
